[tool.ruff.lint]
select = ["ALL"]
# dashed-underline-after-section (D407)
# assert (S101)
ignore = ["D407", "S101"]

[tool.ruff]
exclude = [
    ".git",
    ".mypy_cache",
    ".venv",
]
target-version = "py311"
